### PR TITLE
fix: check offchain inventory before placing counter trades

### LINKED ISSUE #263: Check offchain inventory before placing counter trades
Counter trades placed via `execute_pending_offchain_execution` in `check_and_execute_accumulated_positions` do not verify that the offchain venue has sufficient inventory before placing the order.

For sell orders, the bot should confirm offchain equity is available for the symbol. For buy orders, it should confirm sufficient USDC/cash balance — this requires fetching the current price from the broker (e.g. Alpaca) to estimate the cost. Slippage should be accounted for.

When inventory is insufficient, the execution should be **skipped** (not failed), so the accumulator retries on the next cycle once inventory has settled.

### Affected code

- `check_and_execute_accumulated_positions` in `src/conductor/mod.rs`
- `InventoryView` in `src/inventory/view.rs` (needs `offchain_equity_available` and `offchain_usdc_available` accessors)
- `VenueBalance::available` in `src/inventory/venue_balance.rs` (currently `#[cfg(test)]` only)

### PR DESCRIPTION
**Pull request by findolor**
## Motivation

Closes #263.
Closes [RAI-45](https://linear.app/makeitrain/issue/RAI-45/check-offchain-inventory-before-placing-counter-trades).

Counter-trades were being submitted to Alpaca without proving that the broker
account could actually support them.

That left three concrete gaps:

- sell-side counter-trades could be placed without confirming the broker held
enough shares
- buy-side counter-trades could be preflighted against raw cash instead of
margin-safe buying power
- concurrent submission paths could approve multiple counter-trades against the
same broker capacity before pending orders were recorded

The result was that the bot could still oversubscribe inventory or rely on
margin even though the goal of the issue was explicitly to avoid that.

## Solution

- add Alpaca counter-trade preflight for both broker integrations
- require sell-side preflight to confirm sufficient offchain equity inventory
- require buy-side preflight to use `non_marginable_buying_power`, capped by
available cash, instead of raw cash
- buffer buy-side cost estimation with configurable
`broker.counter_trade_slippage_bps`
- return explicit preflight reservation data so the conductor can reason about
approved broker capacity
- serialize counter-trade submission through a shared in-process lock so the
preflight-to-persist step cannot race across queued and periodic submission
paths
- move the counter-trade gating logic into a dedicated
`src/conductor/counter_trade.rs` module instead of keeping it spread across
the conductor
- remove conductor-side double-counting of already-open Alpaca buy orders once
broker buying power is trusted as the live source of truth
- make USDC rebalance amounts quantize to 6 decimals at the trigger boundary so
execution keeps rejecting lossy financial input instead of silently truncating
it

## Checks

By submitting this for review, I'm confirming I've done the following:

- [x] added comprehensive test coverage for any changes in logic
- [x] made this PR as small as possible
- [x] linked any relevant issues or PRs
- [ ] included screenshots (if this involves a change to the dashboard)

Verification run:

- [x] `nix develop -c cargo check --workspace`
- [x] `nix develop -c cargo nextest run --workspace --all-features`
- [x] `nix develop -c cargo clippy --workspace --all-targets --all-features`
- [x] `nix develop -c cargo fmt --all`

## Anything else

`nextest` finished green, but it reported one flaky retry in the existing e2e
test `hedging::direct_high_precision_sell_price_still_hedges`, which passed on
retry.

This fix is intended for the current single-process deployment model. If we ever
run multiple bot processes against the same broker account, the next step would
be a shared cross-process reservation mechanism.

## Release Notes

* **New Features**
  * Hedging workflow now verifies available equity (sell orders) and buying power (buy orders) before submission
  * Counter-trade submission now coordinates across simultaneous instances

* **Bug Fixes**
  * USDC cryptocurrency orders exceeding 6 decimal places are now rejected

* **Documentation**
  * Added hedging workflow preflight check behaviors and new required broker configuration parameter `counter_trade_slippage_bps`

* **Configuration**
  * New required parameter: `[broker] counter_trade_slippage_bps = 100` (basis-point buffer)

### CODE REVIEW

**Comment by findolor** [comment]
* **#562** <a href="https://app.graphite.com/github/pr/ST0x-Technology/st0x.liquidity/562?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/ST0x-Technology/st0x.liquidity/562?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#570** <a href="https://app.graphite.com/github/pr/ST0x-Technology/st0x.liquidity/570?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#576** <a href="https://app.graphite.com/github/pr/ST0x-Technology/st0x.liquidity/576?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>add-to-gt-merge-queue</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/ST0x-Technology?ref=merge-queue-instructions-in-stack-comment&prId=562).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/execution/src/alpaca_trading_api/inventory.rs [hunk 1]
```diff
@@ -0,0 +1,137 @@
...
+    pub(super) margin_safe_buying_power_cents: i64,
+}
+
+#[derive(Debug, Deserialize)]
+struct PositionResponse {
+    symbol: String,
+    #[serde(
+        rename = "qty",
+        deserialize_with = "deserialize_float_from_number_or_string"
+    )]
```
Comment (JuaniRios) [inline crates/execution/src/alpaca_trading_api/inventory.rs]: Use `qty_available` instead of `qty` to account for earmarked amounts. Same applies to the broker API counterpart in `alpaca_broker_api/positions.rs`.

File: crates/execution/src/alpaca_market_data.rs [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+}
+
+pub(crate) async fn fetch_latest_trade_price(
+    client: &Client,
+    market_data_base_url: &str,
+    symbol: &Symbol,
+) -> Result<Float, AlpacaMarketDataError> {
+    let response: LatestTradeEnvelope = client
+        .get(format!(
+            "{market_data_base_url}/v2/stocks/{symbol}/trades/latest"
```
Comment (JuaniRios) [inline crates/execution/src/alpaca_market_data.rs:43]: Make the return type `Positive<Float>` so zero/negative prices are rejected at construction.

File: crates/execution/src/alpaca_broker_api/positions.rs [hunk 3]
```diff
@@ -33,13 +39,18 @@ struct PositionResponse {
 struct AccountDetailsResponse {
     #[serde(deserialize_with = "deserialize_float_from_number_or_string")]
     cash: Float,
+    #[serde(
+        default,
+        deserialize_with = "deserialize_option_float_from_number_or_string"
+    )]
+    non_marginable_buying_power: Option<Float>,
```
Comment (JuaniRios) [inline crates/execution/src/alpaca_broker_api/positions.rs]: Make `non_marginable_buying_power` required instead of Optional. If Alpaca omits it, we should fail the preflight rather than silently falling back to raw cash. Same applies to the trading API counterpart in `alpaca_trading_api/inventory.rs` although the whole trading api should be removed

File: crates/execution/src/mock.rs [hunk 4]
```diff
@@ -179,6 +190,68 @@ impl Executor for MockExecutor {
 
         Ok(self.inventory_result.clone())
     }
+
+    async fn preflight_counter_trade(
+        &self,
+        order: MarketOrder,
+    ) -> Result<CounterTradePreflight, Self::Error> {
```
Comment (JuaniRios) [inline crates/execution/src/mock.rs:197]: This should check `self.should_fail` before proceeding, like `place_market_order` and `get_inventory` do. Otherwise a mock configured to simulate broker failures still reports the trade as preflight-allowed.

File: crates/execution/src/lib.rs [hunk 5]
```diff
@@ -445,6 +560,18 @@ mod tests {
         assert_eq!(shares.to_whole_shares().unwrap(), 100);
     }
 
+    #[test]
+    fn estimate_buffered_cost_cents_applies_slippage_and_rounds_up() {
```
Comment (JuaniRios) [inline crates/execution/src/lib.rs:537]: This test only uses inputs that land on exact cents, so the round-up branch (`lossless == false`) is never exercised. Add a case with a fractional-cent result, e.g. 1 share at .001 with 1% slippage.

File: src/conductor/counter_trade.rs [hunk 6]
```diff
@@ -0,0 +1,376 @@
...
+
+pub(crate) struct OffchainOrderViews<'a> {
+    pub(crate) store: &'a Store<OffchainOrder>,
+    pub(crate) counter_trade_submission_lock: &'a tokio::sync::Mutex<()>,
+}
+
+impl<'a> OffchainOrderViews<'a> {
+    pub(crate) fn new(
+        store: &'a Store<OffchainOrder>,
+        _projection: &'a Projection<OffchainOrder>,
```
Comment (JuaniRios) [inline src/conductor/counter_trade.rs:29]: The `_projection` parameter is accepted but immediately discarded. Remove it if it is not needed yet.

File: src/rebalancing/trigger/usdc.rs [hunk 7]
```diff
@@ -114,7 +124,13 @@ pub(super) async fn check_imbalance_and_build_operation(
             }
         }
         Imbalance::TooMuchOnchain { excess } => Ok(TriggeredOperation::UsdcBaseToAlpaca {
```
Comment (JuaniRios) [inline src/rebalancing/trigger/usdc.rs]: After truncation the amount can be zero if the excess was below precision. The `TooMuchOffchain` arm has a minimum-withdrawal guard but this arm has nothing. Add a zero check to avoid emitting a no-op transfer.

File: src/conductor/counter_trade.rs [hunk 8]
```diff
@@ -0,0 +1,376 @@
...
+    let order = MarketOrder {
+        symbol: execution.symbol.clone(),
+        shares: execution.shares,
+        direction: execution.direction,
+    };
+
+    match executor.preflight_counter_trade(order).await? {
+        CounterTradePreflight::Allowed { reservation } => {
+            if let (Some(batch_budget), Some(reservation)) = (batch_budget, reservation.as_ref())
+                && let Some(reason) = batch_budget.reserve(reservation)?
```
Comment (JuaniRios) [inline src/conductor/counter_trade.rs:183]: The batch budget is debited here before the order is actually submitted. If the submission fails further down, the reservation is never refunded, which can starve later positions in the same batch. Not urgent since the budget is recreated each cycle, but worth noting.

**Review by JuaniRios — CHANGES_REQUESTED** [review]
Looks good, just a few things to address.
We talked with Josh and Gleb about removing the trading api and schwab since its not going to be used any time soon and adds code maintenance. So please remove it either in this PR or as a parent PR.

**Review by JuaniRios — APPROVED** [review]

**Review by hardyjosh — APPROVED** [review]
